taco_api:
  image: ${API_IMAGE_NAME}:${API_IMAGE_TAG}
  ports:
  - "127.0.0.1:8000:8000"
  volumes:
  - /var/lib/docker/volumes/dbvolume/_data:/db

taco_ui:
  image: ${UI_IMAGE_NAME}:${UI_IMAGE_TAG}
  ports:
  - "80:3000"