taco_api:
  image: 084735579641.dkr.ecr.us-west-2.amazonaws.com/vws_taco_api:latest
  ports:
  - "8000:8000"

taco_ui:
  image: 084735579641.dkr.ecr.us-west-2.amazonaws.com/vws_taco_ui:latest
  ports:
  - "80:3000"
