taco_api:
  image: ${API_IMAGE_NAME}:${API_IMAGE_TAG}
  net: host
  ports:
  - "8000:8000"
  volumes:
  - /var/lib/docker/volumes/dbvolume/_data:/db

taco_ui:
  image: ${UI_IMAGE_NAME}:${UI_IMAGE_TAG}
  environment:
    - API_HOSTNAME
    - HTTPS=false
  ports:
  - "80:3000"
